name: Merge staging to develop

on:
  schedule:
    - cron: '0 45 * * *' # every night
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.6
        with:
          owner: tv2
          head: staging
          base: develop
          pr_title: Automerge staging
          auto_merge: false