name: Sync Fork release37 (currently master) to our develop

on:
  schedule:
    - cron: '15 0 * * 0' # every sunday night
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.6
        with:
          owner: nrkno
          head: master
          base: develop
          pr_title: Automerge NRK release37
          auto_merge: false
