name: Sync Fork nrk/master to our staging

on:
  schedule:
    - cron: '45 23 * * 0' # every sunday night
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.6
        with:
          owner: nrkno
          head: master
          base: staging
          pr_title: Automerge NRK master
          auto_merge: false
